//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soporte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computadora
    {
        public int IDcomputadora { get; set; }
        public string ST { get; set; }
        public string Nro_Serie { get; set; }
        public string Equipo { get; set; }
        public string Lugar { get; set; }
        public string Sector { get; set; }
        public Nullable<int> Nro__Telefono { get; set; }
        public string ST_Monitor { get; set; }
        public string Nro__Serie_Monitor { get; set; }
        public string Sistema_Operativo { get; set; }
        public string Memoria_Ram { get; set; }
        public string Procesador { get; set; }
        public string Observaciones { get; set; }
    }
}
