//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soporte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computadoras
    {
        public int IDcomputadora { get; set; }
        public string ST { get; set; }
        public string numerSerie { get; set; }
        public string Equipo { get; set; }
        public string Lugar { get; set; }
        public string Sector { get; set; }
        public string Telefono { get; set; }
        public string stMonitor { get; set; }
        public string nroSerieMonitor { get; set; }
        public string sistemaOperativo { get; set; }
        public string memoriaRam { get; set; }
        public string Procesador { get; set; }
        public string Observaciones { get; set; }
    }
}
